Projet Tuteure IUT Montpellier: GraphManager Class Reference
GraphManager Class Reference
GraphManager is a class that create and manage some graph. This class can create paramethized undirected graph from a file or randomly.
#include <graphManager.h>
Public Member Functions
GraphManager (void)
This constructor init the object with an empty graph and graphAttributes relative to the graph.
GraphManager (ogdf::String path)
~GraphManager (void)
void genRandomGraph (int n, int e)
This method can generate a random graph.
void addNode (void)
this method add a node to the main graph
void addEdge (void)
this method add an edge to the main graph
ogdf::Graph & getGraph (void)
ogdf::GraphAttributes & getGraphAttribute (void)
graphChild genChild (void)
this function generate a graph and push it in the list of graph child.
void addNodeChild (graphChild &gC, ogdf::node &n)
This method add a node to a graph corresponding to a node of the main graph.
void addEdgeChild (graphChild &gC, ogdf::edge &e)
This method add an edge to a graph corresponding to an edge of the main graph.
std::vector< graphChild > getChildren (void)
void graphDefaultView (void)
void exportGML (ogdf::String path, bool defaultLayout)
this method export the current graph and its attributes to a gml file.
void exportSVG (ogdf::String path, bool defaultLayout)
this method export the current graph and its attributes to a svg file.
void setChildView (graphChild &gC, ogdf::String c="red")
this method set the current graph with some color on the edges and nodes that correspond of the nodes and edges of the graph child.
Private Member Functions
void init (void)
This method permit to share the default constructor code.
Private Attributes
ogdf::Graph graph
ogdf::GraphAttributes graphAttribute
std::vector< graphChild > children
Detailed Description
GraphManager is a class that create and manage some graph. This class can create paramethized undirected graph from a file or randomly.
Constructor & Destructor Documentation
GraphManager::GraphManager (void)
This constructor init the object with an empty graph and graphAttributes relative to the graph.
This constructor init the object with graph and graphAttributes from a gml file.
Parameters
path is the path to the gml file.
References init().
GraphManager::GraphManager (ogdf::String path)
References graph, graphAttribute, and init().
GraphManager::~GraphManager (void)
Member Function Documentation
GraphManager::addEdge (void)
this method add an edge to the main graph
GraphManager::addEdgeChild (graphChild & gC, ogdf::edge & e)
This method add an edge to a graph corresponding to an edge of the main graph.
Parameters
gC the graph child target
e edge from the main graph
References graphChild::edgeOrigin, graphChild::graph, and graphChild::nodeOrigin.
Referenced by main().
GraphManager::addNode (void)
this method add a node to the main graph
GraphManager::addNodeChild (graphChild & gC, ogdf::node & n)
This method add a node to a graph corresponding to a node of the main graph.
Parameters
gC the graph child target
n node from the main graph
References graphChild::graph, and graphChild::nodeOrigin.
Referenced by main().
GraphManager::exportGML (ogdf::String path, bool defaultLayout)
this method export the current graph and its attributes to a gml file.
Parameters
path is the destination path
defaultLayout define if the default layout will be use.
References graph, and graphAttribute.
Referenced by main().
GraphManager::exportSVG (ogdf::String path, bool defaultLayout)
this method export the current graph and its attributes to a svg file.
Parameters
path is the destination path
defaultLayout define if the default layout will be use.
References graph, and graphAttribute.
Referenced by main().
GraphManager::genChild (void)
this function generate a graph and push it in the list of graph child.
Returns
the graphChild generated
References children.
Referenced by main().
GraphManager::genRandomGraph (int n, int e)
This method can generate a random graph.
Parameters
n is the number of nodes.
e is the number of edges.
References graph.
GraphManager::getChildren (void)
Returns
this->children
References children.
GraphManager::getGraph (void)
Returns
this->graph
References graph.
Referenced by main().
GraphManager::getGraphAttribute (void)
Returns
this->graphAttribute
References graphAttribute.
void GraphManager::graphDefaultView (void)
References graph, and graphAttribute.
Referenced by main().
GraphManager::init (void) private
This method permit to share the default constructor code.
References graph, and graphAttribute.
Referenced by GraphManager().
GraphManager::setChildView (graphChild & gC, ogdf::String c = "red")
this method set the current graph with some color on the edges and nodes that correspond of the nodes and edges of the graph child.
Parameters
gC is the graph child
c is the color use to show the graph child. Red by default.
References graphChild::edgeOrigin, graphChild::graph, graphAttribute, and graphChild::nodeOrigin.
Referenced by main().
Member Data Documentation
std::vector<graphChild> GraphManager::children private
Contains all children of the current graph
Referenced by genChild(), and getChildren().
ogdf::Graph GraphManager::graph private
Contains the graph
Referenced by exportGML(), exportSVG(), genRandomGraph(), getGraph(), graphDefaultView(), GraphManager(), and init().
ogdf::GraphAttributes GraphManager::graphAttribute private
Contains the attributes of the graph
Referenced by exportGML(), exportSVG(), getGraphAttribute(), graphDefaultView(), GraphManager(), init(), and setChildView().
The documentation for this class was generated from the following files:
graphUtilities/graphManager.h
graphUtilities/graphManager.cpp